/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkschedulesIndexRouteImport } from './routes/workschedules/index'
import { Route as ShiftsIndexRouteImport } from './routes/shifts/index'
import { Route as RatesIndexRouteImport } from './routes/rates/index'
import { Route as ParkingzonesIndexRouteImport } from './routes/parkingzones/index'
import { Route as ParkingspacesIndexRouteImport } from './routes/parkingspaces/index'
import { Route as MaintenancesIndexRouteImport } from './routes/maintenances/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as CheckoutsIndexRouteImport } from './routes/checkouts/index'
import { Route as AutosIndexRouteImport } from './routes/autos/index'
import { Route as AgreementsIndexRouteImport } from './routes/agreements/index'
import { Route as WorkschedulesCreateRouteImport } from './routes/workschedules/create'
import { Route as ShiftsCreateRouteImport } from './routes/shifts/create'
import { Route as RatesCreateRouteImport } from './routes/rates/create'
import { Route as ParkingzonesInfoRouteImport } from './routes/parkingzones/info'
import { Route as ParkingzonesCreateRouteImport } from './routes/parkingzones/create'
import { Route as ParkingspacesInfoRouteImport } from './routes/parkingspaces/info'
import { Route as ParkingspacesCreateRouteImport } from './routes/parkingspaces/create'
import { Route as MaintenancesCreateRouteImport } from './routes/maintenances/create'
import { Route as IncidentsCreateRouteImport } from './routes/incidents/create'
import { Route as EmployeesCreateRouteImport } from './routes/employees/create'
import { Route as ClientsCreateRouteImport } from './routes/clients/create'
import { Route as CheckoutsCreateRouteImport } from './routes/checkouts/create'
import { Route as AutosCreateRouteImport } from './routes/autos/create'
import { Route as AgreementsCreateRouteImport } from './routes/agreements/create'
import { Route as WorkschedulesShowWs_idRouteImport } from './routes/workschedules/show/$ws_id'
import { Route as WorkschedulesEditWs_idRouteImport } from './routes/workschedules/edit/$ws_id'
import { Route as ShiftsShowSh_idRouteImport } from './routes/shifts/show/$sh_id'
import { Route as ShiftsEditSh_idRouteImport } from './routes/shifts/edit/$sh_id'
import { Route as RatesShowR_idRouteImport } from './routes/rates/show/$r_id'
import { Route as RatesEditR_idRouteImport } from './routes/rates/edit/$r_id'
import { Route as ParkingzonesShowPz_idRouteImport } from './routes/parkingzones/show/$pz_id'
import { Route as ParkingzonesEditPz_idRouteImport } from './routes/parkingzones/edit/$pz_id'
import { Route as ParkingspacesShowPs_idRouteImport } from './routes/parkingspaces/show/$ps_id'
import { Route as ParkingspacesEditPs_idRouteImport } from './routes/parkingspaces/edit/$ps_id'
import { Route as MaintenancesShowM_idRouteImport } from './routes/maintenances/show/$m_id'
import { Route as MaintenancesEditM_idRouteImport } from './routes/maintenances/edit/$m_id'
import { Route as IncidentsShowInc_idRouteImport } from './routes/incidents/show/$inc_id'
import { Route as IncidentsEditInc_idRouteImport } from './routes/incidents/edit/$inc_id'
import { Route as EmployeesShowE_idRouteImport } from './routes/employees/show/$e_id'
import { Route as EmployeesEditE_idRouteImport } from './routes/employees/edit/$e_id'
import { Route as ClientsShowC_idRouteImport } from './routes/clients/show/$c_id'
import { Route as ClientsEditC_idRouteImport } from './routes/clients/edit/$c_id'
import { Route as CheckoutsShowCh_idRouteImport } from './routes/checkouts/show/$ch_id'
import { Route as CheckoutsEditCh_idRouteImport } from './routes/checkouts/edit/$ch_id'
import { Route as AutosShowAt_idRouteImport } from './routes/autos/show/$at_id'
import { Route as AutosEditAt_idRouteImport } from './routes/autos/edit/$at_id'
import { Route as AgreementsShowAg_idRouteImport } from './routes/agreements/show/$ag_id'
import { Route as AgreementsEditAg_idRouteImport } from './routes/agreements/edit/$ag_id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkschedulesIndexRoute = WorkschedulesIndexRouteImport.update({
  id: '/workschedules/',
  path: '/workschedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsIndexRoute = ShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesIndexRoute = RatesIndexRouteImport.update({
  id: '/rates/',
  path: '/rates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingzonesIndexRoute = ParkingzonesIndexRouteImport.update({
  id: '/parkingzones/',
  path: '/parkingzones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingspacesIndexRoute = ParkingspacesIndexRouteImport.update({
  id: '/parkingspaces/',
  path: '/parkingspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancesIndexRoute = MaintenancesIndexRouteImport.update({
  id: '/maintenances/',
  path: '/maintenances/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsIndexRoute = CheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosIndexRoute = AutosIndexRouteImport.update({
  id: '/autos/',
  path: '/autos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsIndexRoute = AgreementsIndexRouteImport.update({
  id: '/agreements/',
  path: '/agreements/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkschedulesCreateRoute = WorkschedulesCreateRouteImport.update({
  id: '/workschedules/create',
  path: '/workschedules/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsCreateRoute = ShiftsCreateRouteImport.update({
  id: '/shifts/create',
  path: '/shifts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesCreateRoute = RatesCreateRouteImport.update({
  id: '/rates/create',
  path: '/rates/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingzonesInfoRoute = ParkingzonesInfoRouteImport.update({
  id: '/parkingzones/info',
  path: '/parkingzones/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingzonesCreateRoute = ParkingzonesCreateRouteImport.update({
  id: '/parkingzones/create',
  path: '/parkingzones/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingspacesInfoRoute = ParkingspacesInfoRouteImport.update({
  id: '/parkingspaces/info',
  path: '/parkingspaces/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingspacesCreateRoute = ParkingspacesCreateRouteImport.update({
  id: '/parkingspaces/create',
  path: '/parkingspaces/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancesCreateRoute = MaintenancesCreateRouteImport.update({
  id: '/maintenances/create',
  path: '/maintenances/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsCreateRoute = IncidentsCreateRouteImport.update({
  id: '/incidents/create',
  path: '/incidents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesCreateRoute = EmployeesCreateRouteImport.update({
  id: '/employees/create',
  path: '/employees/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsCreateRoute = ClientsCreateRouteImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsCreateRoute = CheckoutsCreateRouteImport.update({
  id: '/checkouts/create',
  path: '/checkouts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosCreateRoute = AutosCreateRouteImport.update({
  id: '/autos/create',
  path: '/autos/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsCreateRoute = AgreementsCreateRouteImport.update({
  id: '/agreements/create',
  path: '/agreements/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkschedulesShowWs_idRoute = WorkschedulesShowWs_idRouteImport.update({
  id: '/workschedules/show/$ws_id',
  path: '/workschedules/show/$ws_id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkschedulesEditWs_idRoute = WorkschedulesEditWs_idRouteImport.update({
  id: '/workschedules/edit/$ws_id',
  path: '/workschedules/edit/$ws_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsShowSh_idRoute = ShiftsShowSh_idRouteImport.update({
  id: '/shifts/show/$sh_id',
  path: '/shifts/show/$sh_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsEditSh_idRoute = ShiftsEditSh_idRouteImport.update({
  id: '/shifts/edit/$sh_id',
  path: '/shifts/edit/$sh_id',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesShowR_idRoute = RatesShowR_idRouteImport.update({
  id: '/rates/show/$r_id',
  path: '/rates/show/$r_id',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesEditR_idRoute = RatesEditR_idRouteImport.update({
  id: '/rates/edit/$r_id',
  path: '/rates/edit/$r_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingzonesShowPz_idRoute = ParkingzonesShowPz_idRouteImport.update({
  id: '/parkingzones/show/$pz_id',
  path: '/parkingzones/show/$pz_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingzonesEditPz_idRoute = ParkingzonesEditPz_idRouteImport.update({
  id: '/parkingzones/edit/$pz_id',
  path: '/parkingzones/edit/$pz_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingspacesShowPs_idRoute = ParkingspacesShowPs_idRouteImport.update({
  id: '/parkingspaces/show/$ps_id',
  path: '/parkingspaces/show/$ps_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingspacesEditPs_idRoute = ParkingspacesEditPs_idRouteImport.update({
  id: '/parkingspaces/edit/$ps_id',
  path: '/parkingspaces/edit/$ps_id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancesShowM_idRoute = MaintenancesShowM_idRouteImport.update({
  id: '/maintenances/show/$m_id',
  path: '/maintenances/show/$m_id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancesEditM_idRoute = MaintenancesEditM_idRouteImport.update({
  id: '/maintenances/edit/$m_id',
  path: '/maintenances/edit/$m_id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsShowInc_idRoute = IncidentsShowInc_idRouteImport.update({
  id: '/incidents/show/$inc_id',
  path: '/incidents/show/$inc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsEditInc_idRoute = IncidentsEditInc_idRouteImport.update({
  id: '/incidents/edit/$inc_id',
  path: '/incidents/edit/$inc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesShowE_idRoute = EmployeesShowE_idRouteImport.update({
  id: '/employees/show/$e_id',
  path: '/employees/show/$e_id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEditE_idRoute = EmployeesEditE_idRouteImport.update({
  id: '/employees/edit/$e_id',
  path: '/employees/edit/$e_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsShowC_idRoute = ClientsShowC_idRouteImport.update({
  id: '/clients/show/$c_id',
  path: '/clients/show/$c_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsEditC_idRoute = ClientsEditC_idRouteImport.update({
  id: '/clients/edit/$c_id',
  path: '/clients/edit/$c_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsShowCh_idRoute = CheckoutsShowCh_idRouteImport.update({
  id: '/checkouts/show/$ch_id',
  path: '/checkouts/show/$ch_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsEditCh_idRoute = CheckoutsEditCh_idRouteImport.update({
  id: '/checkouts/edit/$ch_id',
  path: '/checkouts/edit/$ch_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosShowAt_idRoute = AutosShowAt_idRouteImport.update({
  id: '/autos/show/$at_id',
  path: '/autos/show/$at_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutosEditAt_idRoute = AutosEditAt_idRouteImport.update({
  id: '/autos/edit/$at_id',
  path: '/autos/edit/$at_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsShowAg_idRoute = AgreementsShowAg_idRouteImport.update({
  id: '/agreements/show/$ag_id',
  path: '/agreements/show/$ag_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsEditAg_idRoute = AgreementsEditAg_idRouteImport.update({
  id: '/agreements/edit/$ag_id',
  path: '/agreements/edit/$ag_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/workspace': typeof WorkspaceRoute
  '/agreements/create': typeof AgreementsCreateRoute
  '/autos/create': typeof AutosCreateRoute
  '/checkouts/create': typeof CheckoutsCreateRoute
  '/clients/create': typeof ClientsCreateRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/maintenances/create': typeof MaintenancesCreateRoute
  '/parkingspaces/create': typeof ParkingspacesCreateRoute
  '/parkingspaces/info': typeof ParkingspacesInfoRoute
  '/parkingzones/create': typeof ParkingzonesCreateRoute
  '/parkingzones/info': typeof ParkingzonesInfoRoute
  '/rates/create': typeof RatesCreateRoute
  '/shifts/create': typeof ShiftsCreateRoute
  '/workschedules/create': typeof WorkschedulesCreateRoute
  '/agreements': typeof AgreementsIndexRoute
  '/autos': typeof AutosIndexRoute
  '/checkouts': typeof CheckoutsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/maintenances': typeof MaintenancesIndexRoute
  '/parkingspaces': typeof ParkingspacesIndexRoute
  '/parkingzones': typeof ParkingzonesIndexRoute
  '/rates': typeof RatesIndexRoute
  '/shifts': typeof ShiftsIndexRoute
  '/workschedules': typeof WorkschedulesIndexRoute
  '/agreements/edit/$ag_id': typeof AgreementsEditAg_idRoute
  '/agreements/show/$ag_id': typeof AgreementsShowAg_idRoute
  '/autos/edit/$at_id': typeof AutosEditAt_idRoute
  '/autos/show/$at_id': typeof AutosShowAt_idRoute
  '/checkouts/edit/$ch_id': typeof CheckoutsEditCh_idRoute
  '/checkouts/show/$ch_id': typeof CheckoutsShowCh_idRoute
  '/clients/edit/$c_id': typeof ClientsEditC_idRoute
  '/clients/show/$c_id': typeof ClientsShowC_idRoute
  '/employees/edit/$e_id': typeof EmployeesEditE_idRoute
  '/employees/show/$e_id': typeof EmployeesShowE_idRoute
  '/incidents/edit/$inc_id': typeof IncidentsEditInc_idRoute
  '/incidents/show/$inc_id': typeof IncidentsShowInc_idRoute
  '/maintenances/edit/$m_id': typeof MaintenancesEditM_idRoute
  '/maintenances/show/$m_id': typeof MaintenancesShowM_idRoute
  '/parkingspaces/edit/$ps_id': typeof ParkingspacesEditPs_idRoute
  '/parkingspaces/show/$ps_id': typeof ParkingspacesShowPs_idRoute
  '/parkingzones/edit/$pz_id': typeof ParkingzonesEditPz_idRoute
  '/parkingzones/show/$pz_id': typeof ParkingzonesShowPz_idRoute
  '/rates/edit/$r_id': typeof RatesEditR_idRoute
  '/rates/show/$r_id': typeof RatesShowR_idRoute
  '/shifts/edit/$sh_id': typeof ShiftsEditSh_idRoute
  '/shifts/show/$sh_id': typeof ShiftsShowSh_idRoute
  '/workschedules/edit/$ws_id': typeof WorkschedulesEditWs_idRoute
  '/workschedules/show/$ws_id': typeof WorkschedulesShowWs_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/workspace': typeof WorkspaceRoute
  '/agreements/create': typeof AgreementsCreateRoute
  '/autos/create': typeof AutosCreateRoute
  '/checkouts/create': typeof CheckoutsCreateRoute
  '/clients/create': typeof ClientsCreateRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/maintenances/create': typeof MaintenancesCreateRoute
  '/parkingspaces/create': typeof ParkingspacesCreateRoute
  '/parkingspaces/info': typeof ParkingspacesInfoRoute
  '/parkingzones/create': typeof ParkingzonesCreateRoute
  '/parkingzones/info': typeof ParkingzonesInfoRoute
  '/rates/create': typeof RatesCreateRoute
  '/shifts/create': typeof ShiftsCreateRoute
  '/workschedules/create': typeof WorkschedulesCreateRoute
  '/agreements': typeof AgreementsIndexRoute
  '/autos': typeof AutosIndexRoute
  '/checkouts': typeof CheckoutsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/maintenances': typeof MaintenancesIndexRoute
  '/parkingspaces': typeof ParkingspacesIndexRoute
  '/parkingzones': typeof ParkingzonesIndexRoute
  '/rates': typeof RatesIndexRoute
  '/shifts': typeof ShiftsIndexRoute
  '/workschedules': typeof WorkschedulesIndexRoute
  '/agreements/edit/$ag_id': typeof AgreementsEditAg_idRoute
  '/agreements/show/$ag_id': typeof AgreementsShowAg_idRoute
  '/autos/edit/$at_id': typeof AutosEditAt_idRoute
  '/autos/show/$at_id': typeof AutosShowAt_idRoute
  '/checkouts/edit/$ch_id': typeof CheckoutsEditCh_idRoute
  '/checkouts/show/$ch_id': typeof CheckoutsShowCh_idRoute
  '/clients/edit/$c_id': typeof ClientsEditC_idRoute
  '/clients/show/$c_id': typeof ClientsShowC_idRoute
  '/employees/edit/$e_id': typeof EmployeesEditE_idRoute
  '/employees/show/$e_id': typeof EmployeesShowE_idRoute
  '/incidents/edit/$inc_id': typeof IncidentsEditInc_idRoute
  '/incidents/show/$inc_id': typeof IncidentsShowInc_idRoute
  '/maintenances/edit/$m_id': typeof MaintenancesEditM_idRoute
  '/maintenances/show/$m_id': typeof MaintenancesShowM_idRoute
  '/parkingspaces/edit/$ps_id': typeof ParkingspacesEditPs_idRoute
  '/parkingspaces/show/$ps_id': typeof ParkingspacesShowPs_idRoute
  '/parkingzones/edit/$pz_id': typeof ParkingzonesEditPz_idRoute
  '/parkingzones/show/$pz_id': typeof ParkingzonesShowPz_idRoute
  '/rates/edit/$r_id': typeof RatesEditR_idRoute
  '/rates/show/$r_id': typeof RatesShowR_idRoute
  '/shifts/edit/$sh_id': typeof ShiftsEditSh_idRoute
  '/shifts/show/$sh_id': typeof ShiftsShowSh_idRoute
  '/workschedules/edit/$ws_id': typeof WorkschedulesEditWs_idRoute
  '/workschedules/show/$ws_id': typeof WorkschedulesShowWs_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/workspace': typeof WorkspaceRoute
  '/agreements/create': typeof AgreementsCreateRoute
  '/autos/create': typeof AutosCreateRoute
  '/checkouts/create': typeof CheckoutsCreateRoute
  '/clients/create': typeof ClientsCreateRoute
  '/employees/create': typeof EmployeesCreateRoute
  '/incidents/create': typeof IncidentsCreateRoute
  '/maintenances/create': typeof MaintenancesCreateRoute
  '/parkingspaces/create': typeof ParkingspacesCreateRoute
  '/parkingspaces/info': typeof ParkingspacesInfoRoute
  '/parkingzones/create': typeof ParkingzonesCreateRoute
  '/parkingzones/info': typeof ParkingzonesInfoRoute
  '/rates/create': typeof RatesCreateRoute
  '/shifts/create': typeof ShiftsCreateRoute
  '/workschedules/create': typeof WorkschedulesCreateRoute
  '/agreements/': typeof AgreementsIndexRoute
  '/autos/': typeof AutosIndexRoute
  '/checkouts/': typeof CheckoutsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/maintenances/': typeof MaintenancesIndexRoute
  '/parkingspaces/': typeof ParkingspacesIndexRoute
  '/parkingzones/': typeof ParkingzonesIndexRoute
  '/rates/': typeof RatesIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/workschedules/': typeof WorkschedulesIndexRoute
  '/agreements/edit/$ag_id': typeof AgreementsEditAg_idRoute
  '/agreements/show/$ag_id': typeof AgreementsShowAg_idRoute
  '/autos/edit/$at_id': typeof AutosEditAt_idRoute
  '/autos/show/$at_id': typeof AutosShowAt_idRoute
  '/checkouts/edit/$ch_id': typeof CheckoutsEditCh_idRoute
  '/checkouts/show/$ch_id': typeof CheckoutsShowCh_idRoute
  '/clients/edit/$c_id': typeof ClientsEditC_idRoute
  '/clients/show/$c_id': typeof ClientsShowC_idRoute
  '/employees/edit/$e_id': typeof EmployeesEditE_idRoute
  '/employees/show/$e_id': typeof EmployeesShowE_idRoute
  '/incidents/edit/$inc_id': typeof IncidentsEditInc_idRoute
  '/incidents/show/$inc_id': typeof IncidentsShowInc_idRoute
  '/maintenances/edit/$m_id': typeof MaintenancesEditM_idRoute
  '/maintenances/show/$m_id': typeof MaintenancesShowM_idRoute
  '/parkingspaces/edit/$ps_id': typeof ParkingspacesEditPs_idRoute
  '/parkingspaces/show/$ps_id': typeof ParkingspacesShowPs_idRoute
  '/parkingzones/edit/$pz_id': typeof ParkingzonesEditPz_idRoute
  '/parkingzones/show/$pz_id': typeof ParkingzonesShowPz_idRoute
  '/rates/edit/$r_id': typeof RatesEditR_idRoute
  '/rates/show/$r_id': typeof RatesShowR_idRoute
  '/shifts/edit/$sh_id': typeof ShiftsEditSh_idRoute
  '/shifts/show/$sh_id': typeof ShiftsShowSh_idRoute
  '/workschedules/edit/$ws_id': typeof WorkschedulesEditWs_idRoute
  '/workschedules/show/$ws_id': typeof WorkschedulesShowWs_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/reports'
    | '/workspace'
    | '/agreements/create'
    | '/autos/create'
    | '/checkouts/create'
    | '/clients/create'
    | '/employees/create'
    | '/incidents/create'
    | '/maintenances/create'
    | '/parkingspaces/create'
    | '/parkingspaces/info'
    | '/parkingzones/create'
    | '/parkingzones/info'
    | '/rates/create'
    | '/shifts/create'
    | '/workschedules/create'
    | '/agreements'
    | '/autos'
    | '/checkouts'
    | '/clients'
    | '/employees'
    | '/incidents'
    | '/maintenances'
    | '/parkingspaces'
    | '/parkingzones'
    | '/rates'
    | '/shifts'
    | '/workschedules'
    | '/agreements/edit/$ag_id'
    | '/agreements/show/$ag_id'
    | '/autos/edit/$at_id'
    | '/autos/show/$at_id'
    | '/checkouts/edit/$ch_id'
    | '/checkouts/show/$ch_id'
    | '/clients/edit/$c_id'
    | '/clients/show/$c_id'
    | '/employees/edit/$e_id'
    | '/employees/show/$e_id'
    | '/incidents/edit/$inc_id'
    | '/incidents/show/$inc_id'
    | '/maintenances/edit/$m_id'
    | '/maintenances/show/$m_id'
    | '/parkingspaces/edit/$ps_id'
    | '/parkingspaces/show/$ps_id'
    | '/parkingzones/edit/$pz_id'
    | '/parkingzones/show/$pz_id'
    | '/rates/edit/$r_id'
    | '/rates/show/$r_id'
    | '/shifts/edit/$sh_id'
    | '/shifts/show/$sh_id'
    | '/workschedules/edit/$ws_id'
    | '/workschedules/show/$ws_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/reports'
    | '/workspace'
    | '/agreements/create'
    | '/autos/create'
    | '/checkouts/create'
    | '/clients/create'
    | '/employees/create'
    | '/incidents/create'
    | '/maintenances/create'
    | '/parkingspaces/create'
    | '/parkingspaces/info'
    | '/parkingzones/create'
    | '/parkingzones/info'
    | '/rates/create'
    | '/shifts/create'
    | '/workschedules/create'
    | '/agreements'
    | '/autos'
    | '/checkouts'
    | '/clients'
    | '/employees'
    | '/incidents'
    | '/maintenances'
    | '/parkingspaces'
    | '/parkingzones'
    | '/rates'
    | '/shifts'
    | '/workschedules'
    | '/agreements/edit/$ag_id'
    | '/agreements/show/$ag_id'
    | '/autos/edit/$at_id'
    | '/autos/show/$at_id'
    | '/checkouts/edit/$ch_id'
    | '/checkouts/show/$ch_id'
    | '/clients/edit/$c_id'
    | '/clients/show/$c_id'
    | '/employees/edit/$e_id'
    | '/employees/show/$e_id'
    | '/incidents/edit/$inc_id'
    | '/incidents/show/$inc_id'
    | '/maintenances/edit/$m_id'
    | '/maintenances/show/$m_id'
    | '/parkingspaces/edit/$ps_id'
    | '/parkingspaces/show/$ps_id'
    | '/parkingzones/edit/$pz_id'
    | '/parkingzones/show/$pz_id'
    | '/rates/edit/$r_id'
    | '/rates/show/$r_id'
    | '/shifts/edit/$sh_id'
    | '/shifts/show/$sh_id'
    | '/workschedules/edit/$ws_id'
    | '/workschedules/show/$ws_id'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/knowledge-base'
    | '/login'
    | '/register'
    | '/reports'
    | '/workspace'
    | '/agreements/create'
    | '/autos/create'
    | '/checkouts/create'
    | '/clients/create'
    | '/employees/create'
    | '/incidents/create'
    | '/maintenances/create'
    | '/parkingspaces/create'
    | '/parkingspaces/info'
    | '/parkingzones/create'
    | '/parkingzones/info'
    | '/rates/create'
    | '/shifts/create'
    | '/workschedules/create'
    | '/agreements/'
    | '/autos/'
    | '/checkouts/'
    | '/clients/'
    | '/employees/'
    | '/incidents/'
    | '/maintenances/'
    | '/parkingspaces/'
    | '/parkingzones/'
    | '/rates/'
    | '/shifts/'
    | '/workschedules/'
    | '/agreements/edit/$ag_id'
    | '/agreements/show/$ag_id'
    | '/autos/edit/$at_id'
    | '/autos/show/$at_id'
    | '/checkouts/edit/$ch_id'
    | '/checkouts/show/$ch_id'
    | '/clients/edit/$c_id'
    | '/clients/show/$c_id'
    | '/employees/edit/$e_id'
    | '/employees/show/$e_id'
    | '/incidents/edit/$inc_id'
    | '/incidents/show/$inc_id'
    | '/maintenances/edit/$m_id'
    | '/maintenances/show/$m_id'
    | '/parkingspaces/edit/$ps_id'
    | '/parkingspaces/show/$ps_id'
    | '/parkingzones/edit/$pz_id'
    | '/parkingzones/show/$pz_id'
    | '/rates/edit/$r_id'
    | '/rates/show/$r_id'
    | '/shifts/edit/$sh_id'
    | '/shifts/show/$sh_id'
    | '/workschedules/edit/$ws_id'
    | '/workschedules/show/$ws_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AgreementsCreateRoute: typeof AgreementsCreateRoute
  AutosCreateRoute: typeof AutosCreateRoute
  CheckoutsCreateRoute: typeof CheckoutsCreateRoute
  ClientsCreateRoute: typeof ClientsCreateRoute
  EmployeesCreateRoute: typeof EmployeesCreateRoute
  IncidentsCreateRoute: typeof IncidentsCreateRoute
  MaintenancesCreateRoute: typeof MaintenancesCreateRoute
  ParkingspacesCreateRoute: typeof ParkingspacesCreateRoute
  ParkingspacesInfoRoute: typeof ParkingspacesInfoRoute
  ParkingzonesCreateRoute: typeof ParkingzonesCreateRoute
  ParkingzonesInfoRoute: typeof ParkingzonesInfoRoute
  RatesCreateRoute: typeof RatesCreateRoute
  ShiftsCreateRoute: typeof ShiftsCreateRoute
  WorkschedulesCreateRoute: typeof WorkschedulesCreateRoute
  AgreementsIndexRoute: typeof AgreementsIndexRoute
  AutosIndexRoute: typeof AutosIndexRoute
  CheckoutsIndexRoute: typeof CheckoutsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  MaintenancesIndexRoute: typeof MaintenancesIndexRoute
  ParkingspacesIndexRoute: typeof ParkingspacesIndexRoute
  ParkingzonesIndexRoute: typeof ParkingzonesIndexRoute
  RatesIndexRoute: typeof RatesIndexRoute
  ShiftsIndexRoute: typeof ShiftsIndexRoute
  WorkschedulesIndexRoute: typeof WorkschedulesIndexRoute
  AgreementsEditAg_idRoute: typeof AgreementsEditAg_idRoute
  AgreementsShowAg_idRoute: typeof AgreementsShowAg_idRoute
  AutosEditAt_idRoute: typeof AutosEditAt_idRoute
  AutosShowAt_idRoute: typeof AutosShowAt_idRoute
  CheckoutsEditCh_idRoute: typeof CheckoutsEditCh_idRoute
  CheckoutsShowCh_idRoute: typeof CheckoutsShowCh_idRoute
  ClientsEditC_idRoute: typeof ClientsEditC_idRoute
  ClientsShowC_idRoute: typeof ClientsShowC_idRoute
  EmployeesEditE_idRoute: typeof EmployeesEditE_idRoute
  EmployeesShowE_idRoute: typeof EmployeesShowE_idRoute
  IncidentsEditInc_idRoute: typeof IncidentsEditInc_idRoute
  IncidentsShowInc_idRoute: typeof IncidentsShowInc_idRoute
  MaintenancesEditM_idRoute: typeof MaintenancesEditM_idRoute
  MaintenancesShowM_idRoute: typeof MaintenancesShowM_idRoute
  ParkingspacesEditPs_idRoute: typeof ParkingspacesEditPs_idRoute
  ParkingspacesShowPs_idRoute: typeof ParkingspacesShowPs_idRoute
  ParkingzonesEditPz_idRoute: typeof ParkingzonesEditPz_idRoute
  ParkingzonesShowPz_idRoute: typeof ParkingzonesShowPz_idRoute
  RatesEditR_idRoute: typeof RatesEditR_idRoute
  RatesShowR_idRoute: typeof RatesShowR_idRoute
  ShiftsEditSh_idRoute: typeof ShiftsEditSh_idRoute
  ShiftsShowSh_idRoute: typeof ShiftsShowSh_idRoute
  WorkschedulesEditWs_idRoute: typeof WorkschedulesEditWs_idRoute
  WorkschedulesShowWs_idRoute: typeof WorkschedulesShowWs_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workschedules/': {
      id: '/workschedules/'
      path: '/workschedules'
      fullPath: '/workschedules'
      preLoaderRoute: typeof WorkschedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/': {
      id: '/shifts/'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/': {
      id: '/rates/'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingzones/': {
      id: '/parkingzones/'
      path: '/parkingzones'
      fullPath: '/parkingzones'
      preLoaderRoute: typeof ParkingzonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingspaces/': {
      id: '/parkingspaces/'
      path: '/parkingspaces'
      fullPath: '/parkingspaces'
      preLoaderRoute: typeof ParkingspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenances/': {
      id: '/maintenances/'
      path: '/maintenances'
      fullPath: '/maintenances'
      preLoaderRoute: typeof MaintenancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/': {
      id: '/checkouts/'
      path: '/checkouts'
      fullPath: '/checkouts'
      preLoaderRoute: typeof CheckoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autos/': {
      id: '/autos/'
      path: '/autos'
      fullPath: '/autos'
      preLoaderRoute: typeof AutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/': {
      id: '/agreements/'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workschedules/create': {
      id: '/workschedules/create'
      path: '/workschedules/create'
      fullPath: '/workschedules/create'
      preLoaderRoute: typeof WorkschedulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/create': {
      id: '/shifts/create'
      path: '/shifts/create'
      fullPath: '/shifts/create'
      preLoaderRoute: typeof ShiftsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/create': {
      id: '/rates/create'
      path: '/rates/create'
      fullPath: '/rates/create'
      preLoaderRoute: typeof RatesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingzones/info': {
      id: '/parkingzones/info'
      path: '/parkingzones/info'
      fullPath: '/parkingzones/info'
      preLoaderRoute: typeof ParkingzonesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingzones/create': {
      id: '/parkingzones/create'
      path: '/parkingzones/create'
      fullPath: '/parkingzones/create'
      preLoaderRoute: typeof ParkingzonesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingspaces/info': {
      id: '/parkingspaces/info'
      path: '/parkingspaces/info'
      fullPath: '/parkingspaces/info'
      preLoaderRoute: typeof ParkingspacesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingspaces/create': {
      id: '/parkingspaces/create'
      path: '/parkingspaces/create'
      fullPath: '/parkingspaces/create'
      preLoaderRoute: typeof ParkingspacesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenances/create': {
      id: '/maintenances/create'
      path: '/maintenances/create'
      fullPath: '/maintenances/create'
      preLoaderRoute: typeof MaintenancesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/create': {
      id: '/incidents/create'
      path: '/incidents/create'
      fullPath: '/incidents/create'
      preLoaderRoute: typeof IncidentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/create': {
      id: '/employees/create'
      path: '/employees/create'
      fullPath: '/employees/create'
      preLoaderRoute: typeof EmployeesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/create': {
      id: '/clients/create'
      path: '/clients/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof ClientsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/create': {
      id: '/checkouts/create'
      path: '/checkouts/create'
      fullPath: '/checkouts/create'
      preLoaderRoute: typeof CheckoutsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autos/create': {
      id: '/autos/create'
      path: '/autos/create'
      fullPath: '/autos/create'
      preLoaderRoute: typeof AutosCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/create': {
      id: '/agreements/create'
      path: '/agreements/create'
      fullPath: '/agreements/create'
      preLoaderRoute: typeof AgreementsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workschedules/show/$ws_id': {
      id: '/workschedules/show/$ws_id'
      path: '/workschedules/show/$ws_id'
      fullPath: '/workschedules/show/$ws_id'
      preLoaderRoute: typeof WorkschedulesShowWs_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workschedules/edit/$ws_id': {
      id: '/workschedules/edit/$ws_id'
      path: '/workschedules/edit/$ws_id'
      fullPath: '/workschedules/edit/$ws_id'
      preLoaderRoute: typeof WorkschedulesEditWs_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/show/$sh_id': {
      id: '/shifts/show/$sh_id'
      path: '/shifts/show/$sh_id'
      fullPath: '/shifts/show/$sh_id'
      preLoaderRoute: typeof ShiftsShowSh_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/edit/$sh_id': {
      id: '/shifts/edit/$sh_id'
      path: '/shifts/edit/$sh_id'
      fullPath: '/shifts/edit/$sh_id'
      preLoaderRoute: typeof ShiftsEditSh_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/show/$r_id': {
      id: '/rates/show/$r_id'
      path: '/rates/show/$r_id'
      fullPath: '/rates/show/$r_id'
      preLoaderRoute: typeof RatesShowR_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates/edit/$r_id': {
      id: '/rates/edit/$r_id'
      path: '/rates/edit/$r_id'
      fullPath: '/rates/edit/$r_id'
      preLoaderRoute: typeof RatesEditR_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingzones/show/$pz_id': {
      id: '/parkingzones/show/$pz_id'
      path: '/parkingzones/show/$pz_id'
      fullPath: '/parkingzones/show/$pz_id'
      preLoaderRoute: typeof ParkingzonesShowPz_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingzones/edit/$pz_id': {
      id: '/parkingzones/edit/$pz_id'
      path: '/parkingzones/edit/$pz_id'
      fullPath: '/parkingzones/edit/$pz_id'
      preLoaderRoute: typeof ParkingzonesEditPz_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingspaces/show/$ps_id': {
      id: '/parkingspaces/show/$ps_id'
      path: '/parkingspaces/show/$ps_id'
      fullPath: '/parkingspaces/show/$ps_id'
      preLoaderRoute: typeof ParkingspacesShowPs_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkingspaces/edit/$ps_id': {
      id: '/parkingspaces/edit/$ps_id'
      path: '/parkingspaces/edit/$ps_id'
      fullPath: '/parkingspaces/edit/$ps_id'
      preLoaderRoute: typeof ParkingspacesEditPs_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenances/show/$m_id': {
      id: '/maintenances/show/$m_id'
      path: '/maintenances/show/$m_id'
      fullPath: '/maintenances/show/$m_id'
      preLoaderRoute: typeof MaintenancesShowM_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenances/edit/$m_id': {
      id: '/maintenances/edit/$m_id'
      path: '/maintenances/edit/$m_id'
      fullPath: '/maintenances/edit/$m_id'
      preLoaderRoute: typeof MaintenancesEditM_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/show/$inc_id': {
      id: '/incidents/show/$inc_id'
      path: '/incidents/show/$inc_id'
      fullPath: '/incidents/show/$inc_id'
      preLoaderRoute: typeof IncidentsShowInc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/edit/$inc_id': {
      id: '/incidents/edit/$inc_id'
      path: '/incidents/edit/$inc_id'
      fullPath: '/incidents/edit/$inc_id'
      preLoaderRoute: typeof IncidentsEditInc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/show/$e_id': {
      id: '/employees/show/$e_id'
      path: '/employees/show/$e_id'
      fullPath: '/employees/show/$e_id'
      preLoaderRoute: typeof EmployeesShowE_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/edit/$e_id': {
      id: '/employees/edit/$e_id'
      path: '/employees/edit/$e_id'
      fullPath: '/employees/edit/$e_id'
      preLoaderRoute: typeof EmployeesEditE_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/show/$c_id': {
      id: '/clients/show/$c_id'
      path: '/clients/show/$c_id'
      fullPath: '/clients/show/$c_id'
      preLoaderRoute: typeof ClientsShowC_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/edit/$c_id': {
      id: '/clients/edit/$c_id'
      path: '/clients/edit/$c_id'
      fullPath: '/clients/edit/$c_id'
      preLoaderRoute: typeof ClientsEditC_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/show/$ch_id': {
      id: '/checkouts/show/$ch_id'
      path: '/checkouts/show/$ch_id'
      fullPath: '/checkouts/show/$ch_id'
      preLoaderRoute: typeof CheckoutsShowCh_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts/edit/$ch_id': {
      id: '/checkouts/edit/$ch_id'
      path: '/checkouts/edit/$ch_id'
      fullPath: '/checkouts/edit/$ch_id'
      preLoaderRoute: typeof CheckoutsEditCh_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autos/show/$at_id': {
      id: '/autos/show/$at_id'
      path: '/autos/show/$at_id'
      fullPath: '/autos/show/$at_id'
      preLoaderRoute: typeof AutosShowAt_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autos/edit/$at_id': {
      id: '/autos/edit/$at_id'
      path: '/autos/edit/$at_id'
      fullPath: '/autos/edit/$at_id'
      preLoaderRoute: typeof AutosEditAt_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/show/$ag_id': {
      id: '/agreements/show/$ag_id'
      path: '/agreements/show/$ag_id'
      fullPath: '/agreements/show/$ag_id'
      preLoaderRoute: typeof AgreementsShowAg_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/edit/$ag_id': {
      id: '/agreements/edit/$ag_id'
      path: '/agreements/edit/$ag_id'
      fullPath: '/agreements/edit/$ag_id'
      preLoaderRoute: typeof AgreementsEditAg_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  WorkspaceRoute: WorkspaceRoute,
  AgreementsCreateRoute: AgreementsCreateRoute,
  AutosCreateRoute: AutosCreateRoute,
  CheckoutsCreateRoute: CheckoutsCreateRoute,
  ClientsCreateRoute: ClientsCreateRoute,
  EmployeesCreateRoute: EmployeesCreateRoute,
  IncidentsCreateRoute: IncidentsCreateRoute,
  MaintenancesCreateRoute: MaintenancesCreateRoute,
  ParkingspacesCreateRoute: ParkingspacesCreateRoute,
  ParkingspacesInfoRoute: ParkingspacesInfoRoute,
  ParkingzonesCreateRoute: ParkingzonesCreateRoute,
  ParkingzonesInfoRoute: ParkingzonesInfoRoute,
  RatesCreateRoute: RatesCreateRoute,
  ShiftsCreateRoute: ShiftsCreateRoute,
  WorkschedulesCreateRoute: WorkschedulesCreateRoute,
  AgreementsIndexRoute: AgreementsIndexRoute,
  AutosIndexRoute: AutosIndexRoute,
  CheckoutsIndexRoute: CheckoutsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  MaintenancesIndexRoute: MaintenancesIndexRoute,
  ParkingspacesIndexRoute: ParkingspacesIndexRoute,
  ParkingzonesIndexRoute: ParkingzonesIndexRoute,
  RatesIndexRoute: RatesIndexRoute,
  ShiftsIndexRoute: ShiftsIndexRoute,
  WorkschedulesIndexRoute: WorkschedulesIndexRoute,
  AgreementsEditAg_idRoute: AgreementsEditAg_idRoute,
  AgreementsShowAg_idRoute: AgreementsShowAg_idRoute,
  AutosEditAt_idRoute: AutosEditAt_idRoute,
  AutosShowAt_idRoute: AutosShowAt_idRoute,
  CheckoutsEditCh_idRoute: CheckoutsEditCh_idRoute,
  CheckoutsShowCh_idRoute: CheckoutsShowCh_idRoute,
  ClientsEditC_idRoute: ClientsEditC_idRoute,
  ClientsShowC_idRoute: ClientsShowC_idRoute,
  EmployeesEditE_idRoute: EmployeesEditE_idRoute,
  EmployeesShowE_idRoute: EmployeesShowE_idRoute,
  IncidentsEditInc_idRoute: IncidentsEditInc_idRoute,
  IncidentsShowInc_idRoute: IncidentsShowInc_idRoute,
  MaintenancesEditM_idRoute: MaintenancesEditM_idRoute,
  MaintenancesShowM_idRoute: MaintenancesShowM_idRoute,
  ParkingspacesEditPs_idRoute: ParkingspacesEditPs_idRoute,
  ParkingspacesShowPs_idRoute: ParkingspacesShowPs_idRoute,
  ParkingzonesEditPz_idRoute: ParkingzonesEditPz_idRoute,
  ParkingzonesShowPz_idRoute: ParkingzonesShowPz_idRoute,
  RatesEditR_idRoute: RatesEditR_idRoute,
  RatesShowR_idRoute: RatesShowR_idRoute,
  ShiftsEditSh_idRoute: ShiftsEditSh_idRoute,
  ShiftsShowSh_idRoute: ShiftsShowSh_idRoute,
  WorkschedulesEditWs_idRoute: WorkschedulesEditWs_idRoute,
  WorkschedulesShowWs_idRoute: WorkschedulesShowWs_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
